### ISSUE TITLE
puppet-ls description

### ISSUE THREAD

**Issue by RaviTezu** [deanwilson/puppet-scripts#7]
Hi,

puppet-ls description says - lists files that puppet isn't currently managing in the given
directory.
I suspect, it actually lists the files managed by puppet?

**Comment by deanwilson** [comment]
You are completely correct and I've corrected this in [this commit](https://github.com/deanwilson/puppet-scripts/commit/834a8bfb5af2802f03c5c689e03121df76d2dc72)

Apologies for the massive delay in coming back to you on this.

**Comment by RaviTezu** [comment]
@deanwilson Thanks for the commit - I should have raised a pull request :(
