### ISSUE TITLE
puppet-ls do not list some files managed via puppet agent version 3.7.4

### ISSUE THREAD

**Issue by xonicman** [deanwilson/puppet-scripts#9]
Example of file /etc/nagios/nrpe.cfg which is managed via puppet, but list as not-managed by puppet-ls.

puppet agent --version
3.7.4

puppet-ls -i /etc/nagios/
/etc/nagios/nrpe.cfg

Part of /var/lib/puppet/client_yaml/catalog/*.yaml:
#...
   - &id630 !ruby/object:Puppet::Relationship
      source: *id023
      target: &id122 !ruby/object:Puppet::Resource
        catalog: *id001
        exported: false
        file: /etc/puppet/manifests/classes/nagios-nrpe.pp
        line: 23
        parameters:
          !ruby/sym source: puppet:///files/etc/nagios/nrpe.cfg
          !ruby/sym ensure: present
          !ruby/sym path: /etc/nagios/nrpe.cfg
          !ruby/sym require:
            - "Package[nrpe]"
            - "Package[nagios-plugins-nrpe]"
        reference: "File[nrpe.cfg]"
        tags:
          - file
          - nrpe.cfg
          - class
          - nagios-nrpe
          - node
          - default
        title: nrpe.cfg
        type: File
#...

Part of /var/lib/puppet/state/state.yaml:
#...
  File[nrpe.cfg]:
    !ruby/sym synced: 2015-06-19 07:34:26.931604 -07:00
    !ruby/sym checked: 2015-06-19 07:45:09.951312 -07:00
#...

**Comment by deanwilson** [comment]
I'd guess that it's because the file is appearing without its absolute path in the `state.yaml` file. If this is still an issue it'd be handy to see how you're declaring the resource in your puppet manifests.

Apologies for the *very* slow turn around on this issue.
